apiVersion: external-secrets.io/v1
kind: ClusterSecretStore 
metadata:
  name: aws-cluster-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: <area>
      auth:
        jwt: # 假設你用的是 IRSA (OIDC)
          serviceAccountRef:
            name: eso-sa # 這個 SA 也要有權限
            namespace: default # 指定 SA 所在的 namespace
