---
- name: Install Promtail
  hosts: "{{ hosts }}"
  become: yes
  vars_files:
    - "group_vars/promtail_servers.yml"

  tasks:
      # # 這裡因為是封閉環境，會 hang 住，所以不檢查
    # - name: Ensure unzip is installed
    #   ansible.builtin.package:
    #     name: unzip
    #     state: present

    - name: Create Promtail directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ promtail_install_dir }}"
        - "{{ promtail_config_dir }}"
        - "{{ promtail_data_dir }}"

    # 這裡因為是封閉環境，所以會在外部下載好，放到 ec2-user 的目錄下
    # - name: Download Promtail binary
    #   ansible.builtin.get_url:
    #     url: "https://github.com/grafana/loki/releases/download/v{{ promtail_version }}/promtail-linux-amd64.zip"
    #     dest: "{{ promtail_install_base }}/promtail-linux-amd64.zip"
    #     mode: '0644'

    - name: Unzip Promtail
      ansible.builtin.unarchive:
        src: "{{ promtail_install_base }}/promtail-linux-amd64.zip"
        dest: "{{ promtail_install_dir }}"
        remote_src: yes

    - name: Rename and Move binary
      ansible.builtin.command:
        cmd: "mv {{ promtail_install_dir }}/promtail-linux-amd64 {{ promtail_install_dir }}/promtail"
        creates: "{{ promtail_install_dir }}/promtail"

    - name: Create soft link
      ansible.builtin.file:
        src: "{{ promtail_install_dir }}"
        dest: "{{ promtail_link_dir }}"
        state: link

    - name: Deploy Promtail Config
      ansible.builtin.template:
        src: ../templates/promtail.yml.j2
        dest: "{{ promtail_config_dir }}/promtail.yml"
      notify: Restart Promtail

    - name: Deploy Promtail Service
      ansible.builtin.template:
        src: ../templates/promtail.service.j2
        dest: /etc/systemd/system/promtail.service
      notify: Reload Systemd

    - name: Ensure Promtail is started
      ansible.builtin.systemd:
        name: promtail
        state: started
        enabled: yes

    - name: Cleanup zip
      ansible.builtin.file:
        path: "{{ promtail_install_base }}/promtail-linux-amd64.zip"
        state: absent

  handlers:
    - name: Reload Systemd
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Restart Promtail
      ansible.builtin.systemd:
        name: promtail
        state: restarted